# Generated by Django 5.2.17 on 2026-09-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = []

	operations = [
		migrations.CreateModel(
			name="Experience",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
					),
				),
				("role", models.CharField(max_length=150)),
				("organization", models.CharField(max_length=150)),
				("location", models.CharField(max_length=150)),
				("period", models.CharField(max_length=100)),
				("description", models.TextField()),
				("order", models.PositiveIntegerField(default=0)),
			],
			options={
				"ordering": ["order", "id"],
			},
		),
		migrations.CreateModel(
			name="Profile",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
					),
				),
				("name", models.CharField(max_length=120)),
				("role", models.CharField(max_length=150)),
				("summary", models.TextField()),
				("email", models.EmailField(max_length=254)),
				("phone", models.CharField(max_length=30)),
				("location", models.CharField(max_length=120)),
				("github", models.URLField()),
				("linkedin", models.URLField()),
				("skills", models.JSONField(default=list)),
				("education", models.JSONField(default=dict)),
			],
		),
		migrations.CreateModel(
			name="Project",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
					),
				),
				("title", models.CharField(max_length=150, unique=True)),
				("category", models.CharField(max_length=100)),
				("description", models.TextField()),
				("tags", models.JSONField(default=list)),
				("url", models.URLField()),
				("order", models.PositiveIntegerField(default=0)),
			],
			options={
				"ordering": ["order", "id"],
			},
		),
	]
