# Generated by Django 5.2.17 on 2026-09-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("portfolio", "0001_initial"),
	]

	operations = [
		migrations.CreateModel(
			name="ContactMessage",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
					),
				),
				("name", models.CharField(max_length=120)),
				("email", models.EmailField(max_length=254)),
				("message", models.TextField(max_length=5000)),
				("created_at", models.DateTimeField(auto_now_add=True)),
				("is_read", models.BooleanField(default=False)),
			],
			options={
				"ordering": ["-created_at"],
			},
		),
	]
