# Generated by Django 5.2.17 on 2026-09-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("portfolio", "0002_contactmessage"),
	]

	operations = [
		migrations.AddField(
			model_name="profile",
			name="photo",
			field=models.FileField(blank=True, upload_to="portraits/"),
		),
	]
