# Generated by Django 5.2.17 on 2026-09-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("portfolio", "0003_profile_photo"),
	]

	operations = [
		migrations.CreateModel(
			name="RateLimitBucket",
			fields=[
				("key", models.CharField(max_length=80, primary_key=True, serialize=False)),
				("count", models.PositiveBigIntegerField(default=0)),
				("expires_at", models.DateTimeField(db_index=True)),
			],
		),
	]
